name: "Jekyll Example"
description: "This is an example"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
layout: default
baseurl: /jekyll-test
navigation:
- text: Home
  url: /jekyll-test/
- text: Main
  title: Main
  url: /jekyll-test/main
- text: About
  url: /jekyll-test/about