name: "Jekyll Example"
description: "This is an example"

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
layout: default
baseurl: /jekyll-test
navigation:
- text: Home
  title: Home
  url: /
- text: Main
  title: Main
  url: /main/
- text: About
  title: About
  url: /about/
